# Generated by Django 2.1.15 on 2022-04-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_fixture_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='team',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fixture_away_team', to='notifier.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fixture_home_team', to='notifier.Team'),
            preserve_default=False,
        ),
    ]
