# Generated by Django 2.1.15 on 2022-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0005_auto_20220501_1101"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="tour_id",
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="tournament",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
