# Generated by Django 2.1.15 on 2022-05-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_auto_20220501_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='fixture_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='tour_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
