# Generated by Django 2.1.15 on 2022-05-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0008_tournament_country"),
    ]

    operations = []
