# Generated by Django 2.1.15 on 2022-05-03 11:23

from django.db import migrations


fixtures_client = ""


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0009_auto_20220502_1943'),
    ]

    operations = [
    ]
