# Generated by Django 2.1.15 on 2022-05-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0011_auto_20220503_1207"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixture",
            name="fixture_id",
        ),
    ]
