# Generated by Django 2.1.15 on 2022-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0012_remove_fixture_fixture_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="league",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
    ]
