# Generated by Django 2.1.15 on 2022-05-12 20:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0013_auto_20220503_1455"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("round", models.CharField(max_length=255)),
                ("logo", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="fixture",
            name="goals_away",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fixture",
            name="goals_home",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="picture",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fixture",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notifier.League"
            ),
        ),
    ]
