# Generated by Django 2.1.15 on 2022-05-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifier", "0014_auto_20220512_2054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="goals_away",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fixture",
            name="goals_home",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
