# Generated by Django 2.1.15 on 2022-05-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0016_auto_20220512_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255)),
                ('points', models.CharField(max_length=255)),
                ('goals_diff', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='round',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.League'),
        ),
        migrations.AddField(
            model_name='teamstanding',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Team'),
        ),
    ]
