# Generated by Django 2.1.15 on 2022-05-14 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0018_auto_20220514_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='round',
        ),
        migrations.AddField(
            model_name='fixture',
            name='round',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
