# Generated by Django 2.1.15 on 2022-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0019_auto_20220514_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='round',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
