# Generated by Django 2.1.15 on 2022-05-14 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0022_auto_20220514_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstanding',
            name='season',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
