TWILIO_ACCOUNT_SID = "<YOUR_TWILIO_ACC_SID>"
TWILIO_ACCOUNT_TOKEN = "<YOUR_TWILIO_ACC_TOKEN>"

TWILIO_WHATSAPP_NUMBER = "<YOUR_TWILIO_WPP_NUMBER>"

RECIPIENTS = {
    # LIST OF RECIPIENTS IN FORMAT DICT { "Name": "Number" }
}
